name: 'Lint'

on: [push, pull_request]

jobs: 
  lint:
    name: 'Lint'
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Use NodeJS 14
        uses: actions/checkout@v2
        with:
          node-version: 14.x
          registry-url: 'https://registry.npmjs.org'

      - name: Used the cached node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: nodeModules-${{ hashFiles('**/yarn.lock')}}
          restore-keys: |
            nodeModules-

      - name: Install deps
        run: yarn install 
        env:
          CI: true
      
      - name: Run Yarn Lint
        run: yarn lint --fix
        env:
          CI: true

      - name: Type Check (via tsc --noEmit)
        run: yarn tsc --noEmit
